import { describe, it, expect } from 'vitest';
import { isValidMemo, generateShortReference, generateInvoiceMemo } from '../memo';

describe('isValidMemo', () => {
  it('returns true for a standard valid memo', () => {
    expect(isValidMemo('INV-ABC-123')).toBe(true);
    expect(isValidMemo('INV-XYZ-999')).toBe(true);
    expect(isValidMemo('INV-1A2B3C-XYZ789')).toBe(true);
  });

  it('returns true for memo generated by generateInvoiceMemo', () => {
    const memo = generateInvoiceMemo();
    expect(isValidMemo(memo)).toBe(true);
    // Ensure generated format is INV-TIMESTAMP-RANDOM
    expect(memo).toMatch(/^INV-[A-Z0-9]+-[A-Z0-9]+$/);
  });

  it('returns true for numeric-only segments', () => {
    expect(isValidMemo('INV-123-456')).toBe(true);
  });

  it('returns true for single-char segments', () => {
    expect(isValidMemo('INV-A-B')).toBe(true);
  });

  it('returns true for long random segments', () => {
    expect(isValidMemo('INV-' + 'A'.repeat(20) + '-' + 'Z'.repeat(20))).toBe(true);
  });

  it('returns false for empty string', () => {
    expect(isValidMemo('')).toBe(false);
  });

  it('returns false for lowercase memo', () => {
    expect(isValidMemo('inv-abc-123')).toBe(false);
    expect(isValidMemo('INV-abc-123')).toBe(false);
    expect(isValidMemo('INV-ABC-abc')).toBe(false);
  });

  it('returns false when missing INV prefix', () => {
    expect(isValidMemo('ABC-123-XYZ')).toBe(false);
    expect(isValidMemo('INVABC-123')).toBe(false);
    expect(isValidMemo('XINV-ABC-123')).toBe(false);
  });

  it('returns false when missing second segment', () => {
    expect(isValidMemo('INV-ABC')).toBe(false);
    expect(isValidMemo('INV-')).toBe(false);
    expect(isValidMemo('INV-ABC-')).toBe(false);
  });

  it('returns false when empty middle segment', () => {
    expect(isValidMemo('INV--123')).toBe(false);
    expect(isValidMemo('INV-ABC--XYZ')).toBe(false);
  });

  it('returns false with extra segments', () => {
    expect(isValidMemo('INV-ABC-123-EXTRA')).toBe(false);
    expect(isValidMemo('INV-A-B-C')).toBe(false);
  });

  it('returns false with spaces or special chars', () => {
    expect(isValidMemo(' INV-ABC-123')).toBe(false);
    expect(isValidMemo('INV-ABC-123 ')).toBe(false);
    expect(isValidMemo('INV-ABC 123')).toBe(false);
    expect(isValidMemo('INV-ABC-12 3')).toBe(false);
    expect(isValidMemo('INV-ABC-123!')).toBe(false);
    expect(isValidMemo('INV-ABC_123')).toBe(false);
    expect(isValidMemo('INV-ABC-123-')).toBe(false);
  });

  it('returns false for non-string-like but coerced values edge', () => {
    // isValidMemo expects string; passing non-string would be type error, but ensure it handles stringified check
    expect(isValidMemo('INV-abc-123' as string)).toBe(false);
  });

  it('returns false for memo with lowercase after generation manipulation', () => {
    const memo = generateInvoiceMemo().toLowerCase();
    expect(isValidMemo(memo)).toBe(false);
  });
});

describe('generateShortReference', () => {
  it('generates a string of length 10', () => {
    const ref = generateShortReference();
    expect(ref).toHaveLength(10);
  });

  it('generates uppercase alphanumeric (nanoid) reference', () => {
    const ref = generateShortReference();
    // nanoid default alphabet is A-Za-z0-9_- ; after toUpperCase, lowercase become uppercase, _ and - remain
    expect(ref).toMatch(/^[A-Z0-9_-]{10}$/);
    expect(ref).toBe(ref.toUpperCase());
    // Should not contain lowercase
    expect(/[a-z]/.test(ref)).toBe(false);
  });

  it('generates unique references on successive calls', () => {
    const ref1 = generateShortReference();
    const ref2 = generateShortReference();
    const ref3 = generateShortReference();
    expect(ref1).not.toBe(ref2);
    expect(ref1).not.toBe(ref3);
    expect(ref2).not.toBe(ref3);
  });

  it('does not match isValidMemo format (not INV-)', () => {
    const ref = generateShortReference();
    expect(isValidMemo(ref)).toBe(false);
    expect(ref.startsWith('INV-')).toBe(false);
  });

  it('generates many references all of correct length and format', () => {
    for (let i = 0; i < 20; i++) {
      const ref = generateShortReference();
      expect(ref).toHaveLength(10);
      expect(ref).toMatch(/^[A-Z0-9_-]{10}$/);
    }
  });
});

describe('generateInvoiceMemo integration', () => {
  it('generateInvoiceMemo returns string matching isValidMemo and correct length parts', () => {
    const memo = generateInvoiceMemo();
    expect(isValidMemo(memo)).toBe(true);
    const parts = memo.split('-');
    expect(parts[0]).toBe('INV');
    expect(parts.length).toBe(3);
    expect(parts[1].length).toBeGreaterThan(0);
    expect(parts[2].length).toBe(8); // nanoid(8)
  });

  it('generateInvoiceMemo produces unique memos', () => {
    const m1 = generateInvoiceMemo();
    const m2 = generateInvoiceMemo();
    expect(m1).not.toBe(m2);
  });
});
